### ISSUE TITLE
Heads up - Deprecation warning

### ISSUE THREAD

**Issue by morgangraphics** [gantsign/ansible-role-maven#115]
`TASK [ansible-role-maven : create symbolic links] ******************************
task path: /home/<...>/projects/ansible-roles/ansible-role-maven/tasks/main.yml:67
[DEPRECATION WARNING]: evaluating maven_is_default_installation as a bare 
variable, this behaviour will go away and you might need to add |bool to the 
expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle..
 This feature will be removed in version 2.12. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
included: /home/<...>/projects/ansible-roles/ansible-role-maven/tasks/create-symbolic-links.yml for <HOST>
`

**Comment by freemanjp** [comment]
@morgangraphics thanks for raising this issue.

I'm waiting for the 2.22 release of [Molecule](https://github.com/ansible/molecule) (the test framework I'm using), so I can test against Ansible 2.8 (introduced this deprecation warning), before fixing this issue.

**Comment by freemanjp** [comment]
@morgangraphics the Ansible team have made this warning more selective in their [2.8.2](https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#bugfixes) release and this role no longer receives the warning, so I'm closing this issue.
